### ISSUE TITLE
onlyoffice无法完成初始化 for ￥100

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/StackHub#125]
![Image](https://user-images.githubusercontent.com/109707255/210738191-05b9c96e-ca11-46d3-95f2-0f4d2902c781.png)

↑↑↑docker image info

**Comment by Tooy1011** [comment]
onlyoffice在centos上能够正常运行，在ubuntu上无法正常运行
log报错内容如下
![image](https://user-images.githubusercontent.com/81067792/219261397-2e91ff25-a227-45fd-ba6c-6c8739874c79.png)
