### ISSUE TITLE
Ubuntu 20.04  [Gnome] on Aliyun can't used

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/StackHub#130]
**Describe the bug**

It can login to RDP, but desktop black srcreen 

```
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Thu 2023-02-09 16:49:20 CST; 21min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)

Feb 09 16:48:58 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
Feb 09 16:48:58 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 34992)
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ systemd[1]: xrdp.service: start operation timed out. Terminating.
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ xrdp[791]: (791)(139664367138624)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:172.16.228.7 port 3389)
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] xrdp_mm_module_cleanup
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] Closed socket 17 (AF_UNIX)
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ xrdp[1992]: (1992)(139664367138624)[DEBUG] Closed socket 18 (AF_UNIX)
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ systemd[1]: xrdp.service: Failed with result 'timeout'.
Feb 09 16:49:20 iZbp13k3onjp7dukpr85huZ systemd[1]: Stopped xrdp daemon.

```

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
重新在stackhub体系下生产：
