### ISSUE TITLE
华为云需要手动制作镜像

### ISSUE THREAD

**Issue by LalicNine** [Websoft9/StackHub#162]
![3XRW(9A3AR0X{{0GS6JBM7P](https://user-images.githubusercontent.com/109707255/231328704-5867412a-f6bf-43f5-8b91-2e89f349dbbe.png)

在生产镜像过程进行到停止服务器之后就没有后续操作（自动制作镜像，自动跨域复制等），后续操作需要手动进行。

**Comment by qiaofeng1227** [comment]
待调查优化。
