### ISSUE TITLE
访问by http://[ip6] - pay ¥150

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/StackHub#169]
1. install a app on 华为云
2. 配置网络，使其输入ip6地址能够访问

**Comment by zl-go** [comment]
根据华为云官方文档，只有规定地区的区域可以进行ipv6转换，网址为：https://support.huaweicloud.com/usermanual-eip/eip_0006_02.html
可以转化的地区为:
![image](https://github.com/Websoft9/StackHub/assets/62973206/293f7c30-04c1-43e6-b5a8-831d6554fb0f)
步骤：：

1. 手动购买一个华为云服务器
![image](https://github.com/Websoft9/StackHub/assets/62973206/f5c91306-81a3-4f93-9b3d-81a4ca473d08)

2. 购买完后在控制台搜索【弹性公网IP】功能，在列表中对应条目点击【更多】， 点击开启ipv6转换
![image](https://github.com/Websoft9/StackHub/assets/62973206/dba3197d-c92a-4c7f-8578-cded25cc2781)
