### ISSUE TITLE
System Upgrade error on [common]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/stackhub#50]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
TASK [role_common : System Upgrade] ******************************************************************************************************************************************************************************
fatal: [54.227.187.202]: FAILED! => {"changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

```

**Comment by chendelin1982** [comment]
1. Amazon Linux2  core
2. Develop branch for it?

**Comment by qiaofeng1227** [comment]
AmazonLinux  more upgrade to  Amazon Linux 2023:
```
[ec2-user@ip-172-31-12-123 ~]$ cat /etc/system-release
Amazon Linux release 2023 (Amazon Linux)
[ec2-user@ip-172-31-12-123 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"

```

**Comment by qiaofeng1227** [comment]
about amazonlinux 2023:
- Shell has **yum**, ansible yum module error
- Based on Fedora

> https://docs.aws.amazon.com/linux/al2023/ug/relationship-to-fedora.html

**Comment by qiaofeng1227** [comment]
change to amazonlinux 2 , it is ok.
