### ISSUE TITLE
AmazonLinux product  On AWS

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/stackhub#51]
We need to decide which need to update.
- Runtime can not update on docker install
- no sales product how to update？

产品名称 | 状态 | 最后更新 | 二年内订单 | 对应生产任务
-- | -- | -- | -- | --
Data Exploration and Visualization Platform for Superset (Amazon Linux) | Public | 14-Jul-23 | 有 | superset
Cloud Native Database for MariaDB 10.2 (Amazon Linux) | Public | 10-May-23 | 无 |  
Open Observability platform (Amazon Linux) | Public | 10-May-23 | 有 | grafana
Software Load Balancer (Amazon Linux) | Public | 15-Apr-23 | 有 | haproxy
Cloud Native Database for MySQL 8.0 (Amazon Linux) | Public | 15-Apr-23 | 有 | mysql8.0
Cloud Native MQ for Apache RabbitMQ (Amazon Linux) | Public | 15-Apr-23 | 有 | rabbitmq
Cloud Native Database for MariaDB 10.3 (Amazon Linux) | Public | 12-Apr-23 | 有 | mariadb10.3
Cloud Native Database for MySQL 5.6 (Amazon Linux) | Public | 12-Apr-23 | 无 | mysql5.6
Cloud Native Database for DocumentDB 3.2 (Amazon Linux) | Public | 11-Apr-23 | 无 | mongodb3.2
Cloud Native Database for MySQL 5.5 (Amazon Linux) | Public | 10-Apr-23 | 近无 |  
Cloud Native Database for MariaDB 10.4 (Amazon Linux) | Public | 10-Apr-23 | 无 |  
Cloud Native Database for MySQL 5.7 (Amazon Linux) | Public | 9-Apr-23 | 无 |  
Cloud Native In-memory Database for Redis邃｢ 4.0 (Amazon Linux) | Public | 9-Apr-23 | 无 |  
Node.js 10 Runtime for Web App (Amazon Linux) | Public | 9-Apr-23 | 有 |  
Cloud Native MQ for Apache ActiveMQ Powered by Websoft9 (Amazon Linux) | Public | 8-Apr-23 | 有 |  
Cloud Native Database for DocumentDB 3.6 (Amazon Linux) | Public | 8-Apr-23 | 无 |  
Simplest Business Intelligence and Analytics (Amazon Linux) | Public | 8-Apr-23 | 有 |  
Cloud Native In-memory Database for Redis邃｢ 3.0 (Amazon Linux) | Public | 8-Apr-23 | 无 |  
Cloud Native Database for DocumentDB 4.0 (Amazon Linux) | Public | 7-Apr-23 | 无 |  
Cloud Native In-memory Database for Redis邃｢ 5.0 (Amazon Linux) | Public | 7-Apr-23 | 无 |  
Cloud Native In-memory Database for Redis™ 3.2 (Amazon Linux) | Public | 7-Apr-23 | 无 |  
Node.js 13 Runtime for Web App (Amazon Linux) | Public | 7-Apr-23 | 无 |  
Node.js 12 Runtime for Web App (Amazon Linux) | Public | 7-Apr-23 | 无 |  
DevOps Automation Server for Jenkins® (Amazon Linux) | Public | 7-Apr-23 | 有 | jenkins
Amazon Linux 2 with Desktop Xfce | Public | 6-Apr-23 | 无 |  
Cloud Native Database for DocumentDB 3.4 (Amazon Linux) | Public | 6-Apr-23 | 无 |  
Cloud Native Database for DocumentDB 4.4 (Amazon Linux) | Public | 6-Apr-23 | 有 | mongodb4.4
Cloud Native Database for MariaDB 10.5 (Amazon Linux) | Public | 6-Apr-23 | 无 |  
Cloud Native In-memory Database for Redis™ 2.8 (Amazon Linux) | Public | 6-Apr-23 | 无 |  
Amazon Linux 2 with Desktop MATE | Public | 20-Mar-23 | 有 | mate
Node.js 15 Runtime for Web App (Amazon Linux) | Public | 7-Nov-22 | 无 |  
Node.js 16 Runtime for Web App (Amazon Linux) | Public | 7-Nov-22 | 有 |  
Web-based IT environments Automation Platform (Amazon Linux) | Public | 6-Nov-22 | 有 |  
Ruby Runtime with Rails Framework (Amazon Linux) | Public | 4-Nov-22 | 无 |  
Node.js 14 Runtime for Web App (Amazon Linux) | Public | 4-Nov-22 | 近无 |  
Node.js 17 Runtime for Web App (Amazon Linux) | Public | 4-Nov-22 | 有 |  
Cloud Native Database for DocumentDB 5.0 (Amazon Linux) | Public | 4-Nov-22 | 无 |  
Cloud Native In-memory Database for Redis™ 6.0 (Amazon Linux) | Public | 4-Nov-22 | 无 |  
Cloud Native Database for MariaDB 10.6 (Amazon Linux) | Public | 4-Nov-22 | 无 |  
Enterprise E-Commerce Platform (With Sample Data) | Public |   | 有 | magento2.4.6

**Comment by qiaofeng1227** [comment]
We need to decide which need to update.
- Runtime can not update on docker install

**Comment by laozhou0731** [comment]
## 更新
- 业务软件
- 数据库、运行环境、操作系统类：有故障，影响正常使用

## 不更新
- 数据库、 运行环境、 操作系统类
