### ISSUE TITLE
专案：受控机全球网络问题 for ￥100

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/StackHub#99]
**What type of your feature request?**  

- [x] Linux 仓库问题：只使用知名仓库[package and docker image]
- [x] SNAP 问题：YQ 采用其他安装返回，certbot 弃用
- [ ] wget, git clone,curl  连通性
- [x] stackhub 文件的本地化使用
- [x] get_ip.sh 需在受控机上
- [ ] 其他  补充

涉及到的技术要素：

* [delegate_to](https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html)

**Comment by chendelin1982** [comment]
github 加速
```
https://ghproxy.com/https://github.com
```

**Comment by qiaofeng1227** [comment]
参照脚本：https://github.com/Websoft9/StackHub/blob/main/scripts/get_ip.sh

**Comment by qiaofeng1227** [comment]
写一个脚本，当脚本参数 github组织/githubrepo时，找寻最合适的地址执行git clone 下载。
脚本两个参数，第一个参数是 组织项目名， 第二个参数是 路径，当路径为空时，默认下载在当前路径。

**Comment by xyt52** [comment]
> 写一个脚本，当脚本参数 github组织/githubrepo时，找寻最合适的地址执行git clone 下载。 脚本两个参数，第一个参数是 组织项目名， 第二个参数是 路径，当路径为空时，默认下载在当前路径。

```
#!/bin/bash
PATH=()
Projects=()
git_clone(){  
  for(( i=0;i<${#Projects[*]};i++)) do {
      echo "start clone " ${Projects[i]} ${PATH[i]}
	  
	  if [ ${PATH[i]} = "null" ];then
		 git clone https://ghproxy.com/https://github.com/${Projects[i]}.git
	  else
		 git clone https://ghproxy.com/https://github.com/${Projects[i]}.git  ${PATH[i]}
	  fi
  }&done;
}

git_clone
```
